### ISSUE TITLE
Support hiding columns when $grid->setRememberState(FALSE)

### ISSUE THREAD

**Issue by matoni555** [contributte/datagrid#402]
It is possible to support hiding columns while $grid->setRememberState(FALSE) is set?
I use $grid->setRememberState(FALSE) because I don't want to save grid state permanently.

Thank you
Tomáš Matonoha

**Comment by juniwalk** [comment]
@matoni555 Hello,
only way this would be possible is to add information about hidden column into URL. This is something @paveljanda should decide.

**Comment by dakorpar** [comment]
I see this could be useful in url

**Comment by paveljanda** [comment]
There are more looks on that situation (setRememberState(<bool>)). Things, that could maybe stand alone:
1, Use session and remember stuff (in general)
2, Remember filters
3, Remember pagination
4, Remember page
5, Remember per-page
6, Remember hidden columns

And the question is - should they stand alone?

**Comment by dakorpar** [comment]
Well filters and pagination has to it's crucial because you have to be able to copy paste link to someone.
hidden columns could be usefull but it's not crucial...
In setRememberState would also be usefull to define which parts you want to save as well and which maybe not. Also IMHO if something is saved in session as soon as restored url should change to that as well...
