### ISSUE TITLE
Datagrid as component in form component - filter submit bug

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#728]
I have a form component and inside that i am creating datagrid component. When i want to submit a form or add container with button to WebChemistry/Multiplier (its a replicator) the filter is submitted even there is no filter... After filter submit any form operation is skipped (data save, my snippets refresh, etc.)
```
$grid = new DataGrid();
        $this->addComponent($grid, $name);
        $grid->setStrictSessionFilterValues(false);
        $grid->setPagination(false);
        $grid->setRememberState(false);
        $grid->setAutoSubmit(false);
```

Any idea what to do with this bug? Or am i doing something wrong?

**Comment by martingold** [comment]
So basically you have nested forms because the datagrid itself is a form. Not sure if this behavior is indeed supported. Even HTML5 itself [does not support](https://stackoverflow.com/a/26536925) this feature. 

From top of my head, you could modify the datagrid [template](https://github.com/contributte/datagrid/blob/v5.x/src/templates/datagrid.latte) (you do not use filters anyway) in which you would remove the wrapping form of the datagrid.. not sure thou how that would turn out

**Comment by radekdostal** [comment]
```php
public static function removeFormElementsFromDatagrid(string $html): string
{
  return \Nette\Utils\Strings::replace($html, [
    '/<form\s+.*>+/' => '',
    '/<input type="hidden"\s+.*-->/' => '',
    '/<\/form>/' => ''
  ], NULL, 1);
}
```
```
{capture $grid}
  {control grid}
{/capture}
{$grid|removeFormElementsFromDatagrid|noescape}
```

**Comment by BigOHenry** [comment]
Thank you very much. Looks like it works!
