### ISSUE TITLE
[6.x] Reset filter exception

### ISSUE THREAD

**Issue by martenb** [contributte/datagrid#797]
Submitting reset filter button causes TypeError exception...

![image](https://user-images.githubusercontent.com/13311472/58938220-a8d50680-8774-11e9-9727-2bf789b528e5.png)

**Comment by paveljanda** [comment]
Could you please simulat this bug in https://github.com/planette/playground/blob/master/contributte-datagrid/README.md and send me your repo? Thanks!

Or maybe you can send a PR with fix?

**Comment by martenb** [comment]
It looks like, that this is fixed in v6.x branch, I have 6.0.1 in my project, where it is not fixed yet...

**Comment by paveljanda** [comment]
Is it fixed also in `master`? `master` is current development branch.

**Comment by martenb** [comment]
No it is not, i found pull request to v6.x

https://github.com/contributte/datagrid/pull/778

**Comment by jiriermis** [comment]
I have the same issue. If I set `$grid->setRememberState(false);`
the pressing reset filter button gives
TypeError
Argument 1 passed to iterator_to_array() must implement interface Traversable, array given

**Comment by becygroup** [comment]
I have the same issue in v6.1.1 `Argument 1 passed to iterator_to_array() must implement interface Traversable, array given`

**Comment by jaroslavlibal** [comment]
@paveljanda I can confirm the `iterator_to_array()` problem when remember state is set to false. Also for the master branch. However I think it is a different issue than the reported one.

The problem is that the default value in Datagrid::getSessionData() [is an empty array when $key is null and remember state is set to false](https://github.com/contributte/datagrid/blob/master/src/DataGrid.php#L2720). And arrays cannot be passed to iterator_to_array().

So the question is - should the code be rewritten the foreach to $key => $value one like [in the pull request above](https://github.com/contributte/datagrid/pull/778) or replace the empty array with sth like  \EmptyIterator() in the Datagrid::getSessionData() method or something else?

In both solutions mentioned above remains a potential problem when a non iterable will be passed as a default value. Maybe $defaultValue should be Traversable too and the defauld value should not be null? But this is an another problem, I have not checked any consequences so I mention it only for reference at the moment as it does not affect the possibility of mentioned changes.
